# Generated by Django 5.2.12 on 2026-04-07 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("corporate", "0046_rename_customerplan_invoice_overdue_email_sent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="licenseledger",
            old_name="licenses_at_next_renewal",
            new_name="next_renewal_workplace_count",
        ),
        migrations.RenameField(
            model_name="licenseledger",
            old_name="licenses",
            new_name="current_workplace_count",
        ),
    ]
