# Generated by Django 5.2.13 on 2026-04-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corporate", "0047_rename_licenses_fields_to_workplace_count_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerplan",
            name="user_group_billing_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
