# Generated by Django 5.2.13 on 2026-04-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corporate", "0048_customerplan_user_group_billing_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="licenseledger",
            name="current_external_count",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="licenseledger",
            name="next_renewal_external_count",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
